[package]
name = "example-rust-gtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imp = "0.1.0"

[dependencies.gtk]
package = "gtk4"
version = "0.8.2"
features = ["v4_10"]
